insert into departamentos(nombre) values('Artigas');
insert into departamentos(nombre) values('Canelones'); 	
insert into departamentos(nombre) values('Cerro Largo'); 
insert into departamentos(nombre) values('Colonia'); 	
insert into departamentos(nombre) values('Durazno'); 	
insert into departamentos(nombre) values('Flores'); 
insert into departamentos(nombre) values('Florida'); 	
insert into departamentos(nombre) values('Lavalleja');	
insert into departamentos(nombre) values('Maldonado'); 
insert into departamentos(nombre) values('Montevideo');
insert into departamentos(nombre) values('Paysandú'); 
insert into departamentos(nombre) values('Río Negro');
insert into departamentos(nombre) values('Rivera'); 	
insert into departamentos(nombre) values('Rocha'); 	
insert into departamentos(nombre) values('Salto'); 	
insert into departamentos(nombre) values('San José');
insert into departamentos(nombre) values('Soriano'); 
insert into departamentos(nombre) values('Tacuarembó'); 
insert into departamentos(nombre) values('Treinta y Tres');
